apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-arduino
  labels:
    role: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      role: webserver
      app: webserver-arduino
  template:
    metadata:
      labels:
        role: webserver
        app: webserver-arduino
    spec:
      containers:
      - name: apache-webserver
        image: tobi312/php:7.4-apache-arm 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-arduino
  labels:
    app: webserver-arduino
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: webserver-arduino
