apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresarduino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresArduino
  template:
    metadata:
      labels:
        app: postgresArduino
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgresarduino-pv-claim
